### ISSUE TITLE
Slow compile times for "large" for loops

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#263]
I wanted to see what would happen in the diffmpm.py example if I increased n_sin_waves = 4000.  When I do this, the entire compilation process chokes on compute_actuation_0__grad.  However, this is a nearly completely parallelizable for loop (really a map reduce), so this gradient should be fast to compile, I would think?  Is there some way to speed this up?

**Comment by yuanming-hu** [comment]
Since `https://github.com/yuanming-hu/taichi/blob/master/examples/difftaichi/diffmpm.py#L210` uses a static for loop to simplify autodiff, the 4000 iterations will get unrolled, which results in a huge kernel. Let me add a custom AD pass for this reduction case so that you don't need a loop unroll for autodiff.

**Comment by ehannigan** [comment]
What was the final solution on this? Right now, diffmpm.py still uses a static for loop in compute_actuation. Was the custom AD pass added in another example?
