### ISSUE TITLE
Object-oriented programming 

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi#268]
Add support for classes..

**Comment by yuanming-hu** [comment]
Added some basic support. @aespielberg
Two notes:
 - Class methods should be decorated with `ti.classkernel` instead of `ti.kernel`
 - `self` parameter must be annotated with `ti.template()` (will remove this restriction later)

**Comment by yuanming-hu** [comment]
Example: https://github.com/yuanming-hu/taichi/blob/master/tests/python/test_oop.py

**Comment by yuanming-hu** [comment]
`self` no longer needs to be annotated with `ti.template()` starting v0.1.2.

**Comment by aespielberg** [comment]
Actually, there is one more thing I have a question about.  I am trying to let actuators be their own object.  This will let me quickly play with different actuation models (e.g. spring networks).  I populate a list of length n_particles, where entry i holds the Actuator that corresponds to particle i (if one exists).  Call that list self.actuators.

I try the following code:, inside a taichi kernel:

```
    for p in range(0, globals.n_particles):
      actuator = self.actuators[p]
      if actuator != None:
        ctrl = self.pressure_actuation[f, ti.max(0, actuator.get_id())]
        A += actuator.get_actuation(ctrl) 
```

You can see the problem here.  Because p is in a ti kernel, p is an expression, not an integer, and I can't index like this.  Is there any way to index into a list of objects?  This will make it tremendously easier for me to add things like observers and controllers into the loop as well.

**Comment by yuanming-hu** [comment]
Sorry, but Taichi can't compile indexing into python lists. You can instead keep a list of "actuator_type: ti.i32" and implement dynamic dispatch in a data-oriented way, e.g. a series of if statements according to actuator type.

**Comment by aespielberg** [comment]
Okay, switching back to that.  Do you think there is any chance of
supporting this at some time in the future?  Even a mapping from lists to a
very specific type, say, callable functions would be extremely useful.

**Comment by aespielberg** [comment]
I should also note that I'm interested in the case where these mappings are
static at graph compile time and never change.

**Comment by yuanming-hu** [comment]
Yeah this will be supported in the future, but probably not the near future. Supporting this will need some nontrivial modification to the compilation system.

**Comment by aespielberg** [comment]
Okay, good to know.  Thank you.

-Andy S.

**Comment by aespielberg** [comment]
Actually, I was just thinking - I could get around this by using a
ti.static on the range, correct?  Then I'd get ints.

However, this would limit me to systems where I can't change the number of
particles after compilation, and further, compilation will be very slow
because it will manually unroll all the loops.

Is this correct?

**Comment by yuanming-hu** [comment]
Yeah compilation will be extremely slow since you are unrolling thousands of iterations.

**Comment by aespielberg** [comment]
Okay, then I'll avoid.
