### ISSUE TITLE
complex kernel and complex kernel grad for classes

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#273]
Is this currently implemented?  If so, what is the syntax for the decorator?

**Comment by yuanming-hu** [comment]
sorry I forgot to implement this. Will do it tonight.

**Comment by yuanming-hu** [comment]
Btw, you can already define a complex kernel that calls classkernels outside your class.

**Comment by yuanming-hu** [comment]
It seems to me that directly using the original decorators for non-class methods work well:
https://github.com/yuanming-hu/taichi/blob/master/tests/python/test_complex_kernels.py#L52

The caveat is that for the manual gradients you have to invoke `self.func(mul, __gradient=True)` instead of `self.func.grad(mul)` - I'll fix that soon.

**Comment by aespielberg** [comment]
Thank you, this works great!  I have some modular classes now.  Sorry for
all the trouble!

**Comment by yuanming-hu** [comment]
Awesome!!!!
