### ISSUE TITLE
Are "Ragged Arrays" supported?

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#279]
I'm trying to implement a cable actuation model in taichi.  For any given soft body, there can be n different cables that run through it.  Each of these cables can run through any number of particles.  I'm trying to make a tensor that will hold cables x particles.  One thing I can do is assign max num particles of any given cable as space to keep track of each, but this seems wasteful.  Is there any more efficient way I can implement this?

**Comment by yuanming-hu** [comment]
We do have a "dynamic" node for variable-length arrays. However, the documentation and LLVM backend implementation (& testing) is still incomplete, I would suggest just using dense arrays for now.

Since this array is constant and you only need one copy, I would say the wasted space consumption is likely negligible.
